### ISSUE TITLE
For some shows booked in my artist the text area to request ticket price change is not shown

### ISSUE THREAD

**Issue by marceloc10uy** [ilpersi/Popmundo-Utils#2]
**Describe the bug**
When going to upcoming shows and clicking on a show's details button, the textarea with the text to request ticket price adjustment is not always shown. It seems to happen when the date is not double digits for date and month.
for instance (2/4/2024).

**To Reproduce**
1. Go to Artist page
2. Click on upcoming shows button
3. Click on a  show's details link button with date showing as single digits example 2/4/2024
4. Text are is not shown
5. If you check the browser console command it shows and error as well

**Expected behavior**
Show text area showing data to request ticket price change

**Screenshots**
Working example
![image](https://github.com/ilpersi/Popmundo-Utils/assets/40185245/16fbda5d-9e30-40e4-822c-fbe5dc9b5a2a)

Example where it does not work
![image](https://github.com/ilpersi/Popmundo-Utils/assets/40185245/4020a739-f49a-4f02-b4c4-9f793ecbe9cb)

**Desktop (please complete the following information):**
 - iOS
 - Browser chrome
 - Version 120.0.6099.109

**Additional context**

**Comment by ilpersi** [comment]
Good catch! :)

I've just published version 0.5.1 which should fix this. I am not able to reproduce it, let me know if it works.

**Comment by marceloc10uy** [comment]
Yes, the change fixed the issue
